### ISSUE TITLE
佬，我在喵崽用ws连接真寻后，真寻收到的指令奇奇怪怪的

### ISSUE THREAD

**Issue by shayue1** [Zyy955/Lain-plugin#15]
就是这样，我就来这里了，希望佬有时间的时候，顺手搞他一下（
![Image_1701433796049](https://github.com/Zyy955/Lain-plugin/assets/133214188/b24cd045-9141-4435-a585-bbe0cd78e06c)
![Image_1701426324413](https://github.com/Zyy955/Lain-plugin/assets/133214188/ecb8c249-4e0b-46d1-ac91-87fa53077348)
![Screenshot_2023-12-02-02-25-04-953_com tencent mobileqq](https://github.com/Zyy955/Lain-plugin/assets/133214188/bc0478c3-b5fa-49c3-b7b3-9563b146aa6b)

**Comment by Zyy955** [comment]
@xiaoye12123 小叶坏蛋！

**Comment by Zyy955** [comment]
现在修复了吗？
