### ISSUE TITLE
关于群友at其他人却触发bot的问题

### ISSUE THREAD

**Issue by MyNameErala** [Zyy955/Lain-plugin#20]
今天修复的这个bug感觉挺有意思的，可以做到chatgpt-plugin的ai随机回复群内群友，可以当作一个功能来实现吗，这样就可以当作 实现了ai自主回复其他人的表象55，感觉我的bot活起来了😭![image](https://github.com/Zyy955/Lain-plugin/assets/130233534/7432611e-6a77-4802-99de-32168e725b8c)![image](https://github.com/Zyy955/Lain-plugin/assets/130233534/978e5a68-63da-4c35-9d91-08253126d082)

**Comment by Zyy955** [comment]
6

**Comment by Zyy955** [comment]
gpt我记得不是有群管功能吗，这个bug影响蛮大的，你可以在gpt那边改一下 e.atBot＝true

**Comment by MyNameErala** [comment]
好的谢谢大佬，我自己去研究一下 > gpt我记得不是有群管功能吗，这个bug影响蛮大的，你可以在gpt那边改一下 e.atBot＝true
