### ISSUE TITLE
使用shamrock适配器，机器人没反应

### ISSUE THREAD

**Issue by linya72** [Zyy955/Lain-plugin#42]
![Image_1706403109619.png](https://github.com/Zyy955/Lain-plugin/assets/107689301/2a22dc15-75a7-4207-b96f-48c3a22d3599)

**Comment by Zyy955** [comment]
什么版本的shamrock

**Comment by linya72** [comment]
![Image_1706449053138.jpg](https://github.com/Zyy955/Lain-plugin/assets/107689301/c2e6c58b-6b42-4f2f-b678-e424b1d042d1)

**Comment by linya72** [comment]
> 什么版本的shamrock

![Image_1706449053138.jpg](https://github.com/Zyy955/Lain-plugin/assets/107689301/15a952f9-5fdb-4ed7-a25f-058736ece79f)

**Comment by linya72** [comment]
1.0.7.dve6201d12

**Comment by Zyy955** [comment]
请在设置里面关掉cq码
