### ISSUE TITLE
大佬，我这是什么问题？

### ISSUE THREAD

**Issue by catcat138** [Zyy955/Lain-plugin#46]
没有你所说的config.yaml文件，并且这个命令说格式错误，改了token.yaml文件，只有频道可以“/”，而群聊还是得用“#”，我机器人是全域的
![Screenshot_2024-02-02-04-36-00-110_com microsoft emmx-edit](https://github.com/Zyy955/Lain-plugin/assets/119076569/ce29c38f-9dc8-4895-bad1-6d9c1ccc52a3)

![IMG_20240202_043741](https://github.com/Zyy955/Lain-plugin/assets/119076569/2504cc8f-3cd4-422d-ae07-231cfea6f231)

![Image_1706819684439](https://github.com/Zyy955/Lain-plugin/assets/119076569/94ef83c5-f42a-4d31-b2bc-c406fe22d273)
![IMG_20240202_055818](https://github.com/Zyy955/Lain-plugin/assets/119076569/b73121c8-4e1f-4a3a-b8e3-bb6c14cba501)

**Comment by Zyy955** [comment]
![image](https://github.com/Zyy955/Lain-plugin/assets/74231782/8dbf10db-4066-4794-ae25-bd3e96c75996)

```
true
```

抱歉，文档没有及时更新。

**Comment by zhou40138** [comment]
哦，好的谢谢大佬

**Comment by zhou40138** [comment]
> ![image](https://private-user-images.githubusercontent.com/74231782/301645727-8dbf10db-4066-4794-ae25-bd3e96c75996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjE4NjAsIm5iZiI6MTcwNjgyMTU2MCwicGF0aCI6Ii83NDIzMTc4Mi8zMDE2NDU3MjctOGRiZjEwZGItNDA2Ni00Nzk0LWFlMjUtYmQzZTk2Yzc1OTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDIxMDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ODc0N2NjMGY0MmUzNmY0MDMwNDVkNWU2ZmU3OTg1Y2MwYzdmZDAwMzczYWEwNDNjYWQzM2RkNmU2MGMyMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.klWNOesXFi3MapTAv0Z7sxk3gHlvnfuBZKWkRCj5Lv8)
> 
> ```
> Prefix: true
> ```
> 
> 抱歉，文档没有及时更新。

哦好的谢谢

**Comment by zhou40138** [comment]
> ![image](https://private-user-images.githubusercontent.com/74231782/301645727-8dbf10db-4066-4794-ae25-bd3e96c75996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjE4NjAsIm5iZiI6MTcwNjgyMTU2MCwicGF0aCI6Ii83NDIzMTc4Mi8zMDE2NDU3MjctOGRiZjEwZGItNDA2Ni00Nzk0LWFlMjUtYmQzZTk2Yzc1OTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDIxMDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ODc0N2NjMGY0MmUzNmY0MDMwNDVkNWU2ZmU3OTg1Y2MwYzdmZDAwMzczYWEwNDNjYWQzM2RkNmU2MGMyMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.klWNOesXFi3MapTAv0Z7sxk3gHlvnfuBZKWkRCj5Lv8)
> 
> ```
> Prefix: true
> ```
> 
> 抱歉，文档没有及时更新。

那个，大佬能问一下是具体改到哪个位置吗，我好像没看懂，抱歉

**Comment by zhou40138** [comment]
> ![image](https://private-user-images.githubusercontent.com/74231782/301645727-8dbf10db-4066-4794-ae25-bd3e96c75996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjIxMDgsIm5iZiI6MTcwNjgyMTgwOCwicGF0aCI6Ii83NDIzMTc4Mi8zMDE2NDU3MjctOGRiZjEwZGItNDA2Ni00Nzk0LWFlMjUtYmQzZTk2Yzc1OTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDIxMTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OWY5ZWI0NDE1NzM4NTU1ZDlhZTczY2JlNzg2Y2FmNTRhMmQ4ZWY2MmFkYjBmMzVmZjgxZTE3NmM1ZWEzMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dzwcMc-3irXC0klpPo0RnU9yUnx9SAzT9yJCV2p0buk)
> 
> ```
> Prefix: true
> ```
> 
> 抱歉，文档没有及时更新。

没事了没事了，谢谢大佬已经解决了，那config.yaml，这个文件是没了吗？
