### ISSUE TITLE
消息合并转发和戳一戳没反应

### ISSUE THREAD

**Issue by Sakurabluer** [Zyy955/Lain-plugin#51]
设计到转发消息之类得会出现下面图片情况

![QQ图片20240216111023](https://github.com/Zyy955/Lain-plugin/assets/102283052/8c622abb-104b-4a74-924a-53009ab36d85)

**Comment by Sakurabluer** [comment]
麻烦大佬看一下，其他功能都正常就是合并消息不行

**Comment by Zyy955** [comment]
卸载掉这个插件试试？![image](https://github.com/Zyy955/Lain-plugin/assets/74231782/7cbd30c3-200d-469b-ae2d-983d63ff0080)
![307142041ef2983529f7144dfb1f5637](https://github.com/Zyy955/Lain-plugin/assets/74231782/a5f7b140-3694-4629-9309-45359e3bed40)
