### ISSUE TITLE
大佬有没有计划做discord的适配？

### ISSUE THREAD

**Issue by TheTychoStar** [Zyy955/Lain-plugin#9]
现在好像只有TRSS自带了discord支持，但是又不想为了discord再额外运行一个trss云崽。如果喵崽也能支持discord就好了，大佬有没有计划增加一个discord的适配？

**Comment by Zyy955** [comment]
我没有那么多精力去维护这么多适配器，加上我本人并不用这个，当然并不排除以后我会进行适配，但是近段时间不会考虑，我工作很忙最近~

**Comment by TheTychoStar** [comment]
明白了，那就期待大佬什么时候想做又有空的时候吧。
